# Generated by Django 4.1.4 on 2022-12-28 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_project', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
